
<!ELEMENT curriculums (cvEuropass*)>
<!ATTLIST curriculums id ID #REQUIRED>

<!ELEMENT cvEuropass (datos_personales, descripcion, experiencia_laboral, tecnologias, formacion, idiomas)>

	<!ELEMENT datos_personales (nombre, apellidos, sexo, nacionalidad, codigoPais, domicilio, contacto)>
		<!ELEMENT nombre (#PCDATA)>
		<!ELEMENT apellidos (#PCDATA)>
		<!ELEMENT sexo (#PCDATA)>
		<!ELEMENT nacionalidad (#PCDATA)>
		<!ELEMENT codigoPais (#PCDATA)>

		<!ELEMENT domicilio (numero, calle, codigoPostal, ciudad)>
			<!ELEMENT numero (#PCDATA)>
			<!ELEMENT calle (#PCDATA)>
			<!ELEMENT codigoPostal (#PCDATA)>
			<!ELEMENT ciudad (#PCDATA)>

		<!ELEMENT contacto (correo, telefono)>
			<!ELEMENT correo (#PCDATA)>
			<!ELEMENT telefono (#PCDATA)>

	<!ELEMENT descripcion (#PCDATA)>
         
	<!ELEMENT experiencia_laboral (experiecia)*>
		<!ELEMENT experiecia (puesto, centro)>
		<!ATTLIST experiecia inicio CDATA #REQUIRED>
		<!ATTLIST experiecia fin CDATA #IMPLIED>
		<!ATTLIST experiecia actual (true | false) #IMPLIED>
			<!ELEMENT puesto (#PCDATA)>
			<!ELEMENT centro (#PCDATA)>

         
	<!ELEMENT tecnologias (tecnologia)*>
		<!ELEMENT tecnologia (#PCDATA)>
		<!ATTLIST tecnologia nivel (básico | intermedio | avanzado) #REQUIRED>
		 
	<!ELEMENT formacion (curso)+>
		<!ELEMENT curso (titulacion?, centro?)>
		<!ATTLIST curso inicio CDATA #REQUIRED>
		<!ATTLIST curso fin CDATA #IMPLIED>
		<!ATTLIST curso actual (true | false) #IMPLIED>
			<!ELEMENT titulacion (#PCDATA)>
			<!ELEMENT centro (#PCDATA)>
			
	<!ELEMENT idiomas (codigoIdioma+)>
		<!ELEMENT codigoIdioma (#PCDATA)>
		<!ATTLIST codigoIdioma nivel CDATA #REQUIRED>
